// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjzgnlwrrofcegvxeiye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqemdubHdycm9mY2VndnhlaXllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNTY0MTIsImV4cCI6MjA1OTYzMjQxMn0.I2z32EhwQHxIvZsT46vw6lc_nNVCnkmcE8Gjq6L1xrw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);